global:
  scrape_interval: 15s
scrape_configs:
  - job_name: coworkspace
    static_configs:
      - targets: ['api-gateway:3000', 'membership-service:3001', 'space-service:3002', 'booking-service:3003', 'billing-service:3004']
